version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - DATABASE_URL=postgresql://user:password@db/apptrackerdb
    depends_on:
      - db
    command: >
      sh -c "python app/wait_for_db.py && 
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=apptrackerdb
    ports:
      - "5432:5432"

volumes:
  postgres_data: 